def stage(stage):
    if stage == 0:
        print()
        print("Pour avoir une lettre gratuite écrivez 'lettre'.")
        print("Pour avoir la description du mot écrivez 'desc'.")
        print()
        print(" __________")
        print(" |        |")
        print(" |         ")
        print(" |         ")
        print(" |         ")
        print(" |         ")
        print(" |         ")
        print("_|____________")
        print("")
    elif stage == 1:
        print()
        print("Pour avoir une lettre gratuite écrivez 'lettre'.")
        print("Pour avoir la description du mot écrivez 'desc'.")
        print()
        print(" __________")
        print(" |        |")
        print(" |        o")
        print(" |         ")
        print(" |         ")
        print(" |         ")
        print(" |         ")
        print("_|____________")
        print()
    elif stage == 2:
        print()
        print("Pour avoir une lettre gratuite écrivez 'lettre'.")
        print("Pour avoir la description du mot écrivez 'desc'.")
        print()
        print(" __________")
        print(" |        |")
        print(" |        o")
        print(" |        | ")
        print(" |         ")
        print(" |         ")
        print(" |         ")
        print("_|____________")
        print()
    elif stage == 3:
        print()
        print("Pour avoir une lettre gratuite écrivez 'lettre'.")
        print("Pour avoir la description du mot écrivez 'desc'.")
        print()
        print(" __________")
        print(" |        |")
        print(" |        o")
        print(" |       -| ")
        print(" |         ")
        print(" |         ")
        print(" |         ")
        print("_|____________")
        print()
    elif stage == 4:
        print()
        print("Pour avoir une lettre gratuite écrivez 'lettre'.")
        print("Pour avoir la description du mot écrivez 'desc'.")
        print()
        print(" __________")
        print(" |        |")
        print(" |        o")
        print(" |       -|- ")
        print(" |         ")
        print(" |         ")
        print(" |         ")
        print("_|____________")
        print()
    elif stage == 5:
        print()
        print("Pour avoir une lettre gratuite écrivez 'lettre'.")
        print("Pour avoir la description du mot écrivez 'desc'.")
        print()
        print(" __________")
        print(" |        |")
        print(" |        o")
        print(" |       -|- ")
        print(" |       / ")
        print(" |         ")
        print(" |         ")
        print("_|____________")
        print()